[project]
name = "ECOAutomation"
dependencies = [
"numpy",
"matplotlib",
"alive-progress",
"gitpython",
"pyyaml"
]
version = "0.1.0"
description = "A package for automating the ECO process"
